{"name": "test_create_vdc", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'wuz_vdc_uiauto_001' in 'vdc01\\n河南分公司\\n有效\\n2019-10-15 01:24:06\\n可用区 更多'", "trace": "self = <test_10_craete_vdc.TestCreateVDC object at 0x009C70F0>\n\n    @pytest.mark.flaky(reruns=3)\n    def test_create_vdc(self):\n        vdc_a = vdcAction.VdcACction(self.dr)\n        vdc_pg = vdcPage.VdcPage(self.dr)\n        login = Login(self.dr)\n        datas = datainfo.get_xls_to_dict(\"user.xlsx\", \"Sheet1\")[0]\n        p_data = datainfo.get_xls_to_dict(\"vdc_vpool.xlsx\",\"Sheet1\")[0]\n        login.login(datas[\"username\"], datas[\"password\"])\n        vdc_a.ceate_vdc(p_data[\"vdcname\"])\n        vdc_pg.open_vdc_page()\n        vdc_pg.search_vdc(p_data[\"vdcname\"])\n        #校验能查询到\n        text = self.dr.get_text(\"xpath->//div[@class='box-body']/table-component/div/table/tbody\")\n>       assert p_data[\"vdcname\"] in text\nE       AssertionError: assert 'wuz_vdc_uiauto_001' in 'vdc01\\n河南分公司\\n有效\\n2019-10-15 01:24:06\\n可用区 更多'\n\ntestcase\\test_10_craete_vdc.py:33: AssertionError"}, "attachments": [{"name": "log", "source": "2364b990-b1ee-46b1-ad34-a18d754c08e3-attachment.txt", "type": "text/plain"}], "start": 1572686785387, "stop": 1572686793243, "uuid": "1c777019-c60e-43d8-a64c-b435de238571", "historyId": "923cb143f731349d5e04c092a5921a20", "testCaseId": "c25d28231a4a9e413e7216051d70a178", "fullName": "testcase.test_10_craete_vdc.TestCreateVDC#test_create_vdc", "labels": [{"name": "parentSuite", "value": "testcase"}, {"name": "suite", "value": "test_10_craete_vdc"}, {"name": "subSuite", "value": "TestCreateVDC"}, {"name": "host", "value": "wuzs"}, {"name": "thread", "value": "18804-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcase.test_10_craete_vdc"}]}